#!/usr/bin/env python
import os
import sys

path = os.getcwd()
num = sys.argv[1]

dict = {}
file_list = os.listdir(path)
for i in range(len(file_list)):
    dict[file_list[i]] = os.path.getmtime(path + "/" + file_list[i])
    sorted_list = sorted(dict.items(), key=lambda e:e[1])

for i in range(int(num)):
    print(sorted_list[i][0])








